# ตั้งชื่อแอปพลิเคชัน
spring.application.name=lab7

# ตั้งค่าการเชื่อมต่อ PostgreSQL (เช็ค Port และชื่อ Database ให้ตรงกับที่สร้างใน pgAdmin)
spring.datasource.url=jdbc:postgresql://localhost:5432/lab7
spring.datasource.username=postgres
spring.datasource.password=23452345

# ตั้งค่า Hibernate / JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect